# -*- coding: utf-8 -*-
"""algoritmoDeOmar

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14KIKoAwHp_tPqnir82fjqdI9rfc__69x
"""

import UtilityFunctions as uf

def algoritmoDeOmar(G):
    #Por ahora para el hito 3...
    return None